In [1]:
import pandas as pd
import numpy as np

In [2]:
data_url = "http://lib.stat.cmu.edu/datasets/boston"
raw_df = pd.read_csv(data_url, sep="\\s+", skiprows=22, header=None)
data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])


In [8]:
data

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [9]:
target = raw_df.values[1::2,2]
target

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [23]:
np.random.seed(22)
x = np.random.uniform(-3,3,size=100)
x

array([-1.74923678, -0.10991363, -0.47677179,  2.15509199, -1.97303068,
       -0.96681624, -1.376803  ,  1.1462481 , -1.6775729 ,  1.87170552,
       -2.93683875,  0.36722218,  1.88235712,  1.47060178, -1.86533187,
       -2.9631548 ,  1.63226323,  2.74699301,  1.2116273 , -1.2145304 ,
        1.60795645,  1.12930995, -0.67689912,  0.69123495, -0.43466856,
        0.50573786,  1.21581311, -2.32862897,  2.53961956,  2.93331764,
        1.06446464,  1.77098865, -2.8255419 , -1.93344557,  2.24956647,
        1.46959246,  0.04854098, -2.22999659, -0.09429457,  0.09464093,
       -1.13241202, -2.72603074, -0.37391604, -2.42469234, -2.72873933,
        1.10897231,  2.09514447, -2.2487569 , -2.22561596, -0.16163999,
       -1.81464895,  1.68973649,  0.64448318, -0.33899943,  2.89217465,
        1.25373248, -1.68761751, -1.99507021,  0.23259284, -1.11947527,
        2.46922198, -2.48246592, -1.11555582, -1.68517583,  1.41999738,
        1.97124219,  1.46738678, -1.93477777,  2.15071918, -2.96

In [25]:
y=0.5 * x ** 2 + x+2+np.random.normal(0,1,size=100)
y

array([ 2.22950644,  3.59367463,  1.77365279,  6.23850772,  2.87893135,
        1.09809278,  0.49697164,  5.85791759,  0.77007872,  5.94336596,
        3.97796407,  2.27783636,  7.72428749,  6.66689212,  2.4672392 ,
        2.03977269,  5.52053548,  6.91540078,  4.67785958,  2.543779  ,
        5.38412957,  5.20943477,  1.90154033,  2.14838484,  1.34575815,
        3.88801617,  1.84085005,  2.72495363,  6.52213332, 11.61639451,
        2.09961582,  2.99184537,  4.08934839,  2.78244457,  5.94907889,
        4.27215815,  0.5317234 ,  1.92073284,  2.62314479,  2.2555282 ,
        1.30597297,  2.24126255,  2.73364662,  4.29820324,  4.43429124,
        2.35358526,  6.49163433,  1.45044925,  1.93563074,  2.33035134,
        4.6798259 ,  5.51487595,  2.94520931,  1.27915178,  9.77569427,
        2.44085302,  2.56678345,  3.01004823,  1.38793322,  3.26969908,
        9.98581654,  1.90315482,  2.43886084,  1.34659681,  3.8189222 ,
        6.88813657,  5.00815492,  0.70552082,  4.99250464,  3.75

In [17]:
x1=x.reshape(-1,1)
x1

array([[-1.74923678],
       [-0.10991363],
       [-0.47677179],
       [ 2.15509199],
       [-1.97303068],
       [-0.96681624],
       [-1.376803  ],
       [ 1.1462481 ],
       [-1.6775729 ],
       [ 1.87170552],
       [-2.93683875],
       [ 0.36722218],
       [ 1.88235712],
       [ 1.47060178],
       [-1.86533187],
       [-2.9631548 ],
       [ 1.63226323],
       [ 2.74699301],
       [ 1.2116273 ],
       [-1.2145304 ],
       [ 1.60795645],
       [ 1.12930995],
       [-0.67689912],
       [ 0.69123495],
       [-0.43466856],
       [ 0.50573786],
       [ 1.21581311],
       [-2.32862897],
       [ 2.53961956],
       [ 2.93331764],
       [ 1.06446464],
       [ 1.77098865],
       [-2.8255419 ],
       [-1.93344557],
       [ 2.24956647],
       [ 1.46959246],
       [ 0.04854098],
       [-2.22999659],
       [-0.09429457],
       [ 0.09464093],
       [-1.13241202],
       [-2.72603074],
       [-0.37391604],
       [-2.42469234],
       [-2.72873933],
       [ 1

In [26]:
x2 = np.hstack([x1,x1**2])
x2

array([[-1.74923678e+00,  3.05982930e+00],
       [-1.09913629e-01,  1.20810059e-02],
       [-4.76771788e-01,  2.27311338e-01],
       [ 2.15509199e+00,  4.64442149e+00],
       [-1.97303068e+00,  3.89285006e+00],
       [-9.66816236e-01,  9.34733635e-01],
       [-1.37680300e+00,  1.89558650e+00],
       [ 1.14624810e+00,  1.31388471e+00],
       [-1.67757290e+00,  2.81425084e+00],
       [ 1.87170552e+00,  3.50328157e+00],
       [-2.93683875e+00,  8.62502187e+00],
       [ 3.67222180e-01,  1.34852129e-01],
       [ 1.88235712e+00,  3.54326834e+00],
       [ 1.47060178e+00,  2.16266958e+00],
       [-1.86533187e+00,  3.47946298e+00],
       [-2.96315480e+00,  8.78028638e+00],
       [ 1.63226323e+00,  2.66428325e+00],
       [ 2.74699301e+00,  7.54597059e+00],
       [ 1.21162730e+00,  1.46804073e+00],
       [-1.21453040e+00,  1.47508409e+00],
       [ 1.60795645e+00,  2.58552395e+00],
       [ 1.12930995e+00,  1.27534096e+00],
       [-6.76899118e-01,  4.58192416e-01],
       [ 6.

In [20]:
x3 = x.reshape(5, 4, 5)
print(x3)

[[[-1.74923678 -0.10991363 -0.47677179  2.15509199 -1.97303068]
  [-0.96681624 -1.376803    1.1462481  -1.6775729   1.87170552]
  [-2.93683875  0.36722218  1.88235712  1.47060178 -1.86533187]
  [-2.9631548   1.63226323  2.74699301  1.2116273  -1.2145304 ]]

 [[ 1.60795645  1.12930995 -0.67689912  0.69123495 -0.43466856]
  [ 0.50573786  1.21581311 -2.32862897  2.53961956  2.93331764]
  [ 1.06446464  1.77098865 -2.8255419  -1.93344557  2.24956647]
  [ 1.46959246  0.04854098 -2.22999659 -0.09429457  0.09464093]]

 [[-1.13241202 -2.72603074 -0.37391604 -2.42469234 -2.72873933]
  [ 1.10897231  2.09514447 -2.2487569  -2.22561596 -0.16163999]
  [-1.81464895  1.68973649  0.64448318 -0.33899943  2.89217465]
  [ 1.25373248 -1.68761751 -1.99507021  0.23259284 -1.11947527]]

 [[ 2.46922198 -2.48246592 -1.11555582 -1.68517583  1.41999738]
  [ 1.97124219  1.46738678 -1.93477777  2.15071918 -2.96692553]
  [-0.85414098  2.71888949  2.65065832 -2.86170592  1.03809598]
  [-2.015314    0.40879422 -1.5472

In [21]:
x3.shape

(5, 4, 5)

In [22]:
print("First few elements of x3:\n", x3)

First few elements of x3:
 [[[-1.74923678 -0.10991363 -0.47677179  2.15509199 -1.97303068]
  [-0.96681624 -1.376803    1.1462481  -1.6775729   1.87170552]
  [-2.93683875  0.36722218  1.88235712  1.47060178 -1.86533187]
  [-2.9631548   1.63226323  2.74699301  1.2116273  -1.2145304 ]]

 [[ 1.60795645  1.12930995 -0.67689912  0.69123495 -0.43466856]
  [ 0.50573786  1.21581311 -2.32862897  2.53961956  2.93331764]
  [ 1.06446464  1.77098865 -2.8255419  -1.93344557  2.24956647]
  [ 1.46959246  0.04854098 -2.22999659 -0.09429457  0.09464093]]

 [[-1.13241202 -2.72603074 -0.37391604 -2.42469234 -2.72873933]
  [ 1.10897231  2.09514447 -2.2487569  -2.22561596 -0.16163999]
  [-1.81464895  1.68973649  0.64448318 -0.33899943  2.89217465]
  [ 1.25373248 -1.68761751 -1.99507021  0.23259284 -1.11947527]]

 [[ 2.46922198 -2.48246592 -1.11555582 -1.68517583  1.41999738]
  [ 1.97124219  1.46738678 -1.93477777  2.15071918 -2.96692553]
  [-0.85414098  2.71888949  2.65065832 -2.86170592  1.03809598]
  [-2.0